import { Link } from 'react-router-dom';
import BrandLogo from '../components/BrandLogo';
import './Landing.css';

const Landing = () => (
  <main className="landing">
    <nav className="landing-nav"><Link className="brand" to="/"><BrandLogo /></Link><div className="nav-actions"><Link className="nav-login" to="/login">Log in</Link><Link className="nav-signup" to="/signup">Get started <span>&rarr;</span></Link></div></nav>
    <section className="hero">
      <div className="hero-copy"><p className="eyebrow"><span /> MADE FOR BETTER CONVERSATIONS</p><h1>Where every<br/><em>conversation</em> flows.</h1><p className="hero-text">A calm, delightful place to connect with the people who matter. Share ideas, make plans, and stay close - all in one space.</p><div className="hero-buttons"><Link className="primary-cta" to="/signup">Start chatting free <span>&rarr;</span></Link><Link className="secondary-cta" to="/login">I have an account</Link></div><p className="small-note">No credit card needed <i /> Ready in seconds</p></div>
      <div className="chat-preview" aria-label="SyncChat interface preview"><div className="preview-top"><div className="tiny-brand"><BrandLogo compact /> SyncChat</div><div>...</div></div><div className="preview-body"><aside><div className="search">Search</div><p>MESSAGES</p><div className="person active"><b>AM</b><span><strong>Amelia Morgan</strong><small>That sounds perfect!</small></span><i /></div><div className="person"><b className="orange">JK</b><span><strong>Jordan Kim</strong><small>See you tomorrow</small></span></div><div className="person"><b className="green">TH</b><span><strong>Team Horizon</strong><small>3 new messages</small></span></div></aside><div className="messages"><header><b>Amelia Morgan</b><small><i /> Online</small></header><div className="message-area"><div className="bubble incoming">Hey! How is the new project coming along?<small>10:24 AM</small></div><div className="bubble outgoing">Really well! I cannot wait to show you what we have been working on.<small>10:26 AM</small></div><div className="bubble incoming">That sounds perfect!<small>10:27 AM</small></div></div><div className="composer">Write a message <span>Send</span></div></div></div></div>
    </section>
    <section className="trust"><p>Everything you need to stay in Sync</p><div><article><span>01</span><h2>Real-time messaging</h2><p>Conversations that move as fast as you do.</p></article><article><span>02</span><h2>Your space, your way</h2><p>Simple, thoughtful, and built around you.</p></article><article><span>03</span><h2>Stay connected</h2><p>Feel close, even when you are far apart.</p></article></div></section>
    <section className="details"><div className="details-copy"><p className="eyebrow"><span /> DESIGNED FOR CONNECTION</p><h2>Less noise. More of what matters.</h2><p>SyncChat gives every conversation room to breathe. Bring your closest people, projects, and plans into one beautifully focused place.</p><Link to="/signup">Create your free account <span>&rarr;</span></Link></div><div className="benefit-grid"><article><b>01</b><h3>Private by default</h3><p>Your conversations stay between the people in them.</p></article><article><b>02</b><h3>Groups that work</h3><p>Make space for your teams, friends, and communities.</p></article><article><b>03</b><h3>Always in the loop</h3><p>See who is around and catch up on every moment.</p></article><article><b>04</b><h3>Simply delightful</h3><p>A fast, distraction-free home for every message.</p></article></div></section>
    <section className="closing"><div><p className="eyebrow"><span /> START TODAY</p><h2>Good conversations<br/>start <em>here.</em></h2></div><Link className="primary-cta" to="/signup">Get started for free <span>&rarr;</span></Link></section>
    <footer className="site-footer"><div><Link className="brand" to="/"><BrandLogo /></Link><p>Thoughtful conversations, always in sync.</p></div><div className="footer-links"><div><b>Product</b><Link to="/signup">Features</Link><Link to="/signup">Get started</Link></div><div><b>Account</b><Link to="/login">Log in</Link><Link to="/signup">Create account</Link></div></div><p className="copyright">Copyright 2026 SyncChat. Built for connection.</p></footer>
  </main>
);
export default Landing;
